config/routes.rb
Rails.application.routes.draw do
  resources :employes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employe.rb
class Employe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employes_controller.rb
class EmployesController < ApplicationController
  before_action :set_employe, only: [:show, :edit, :update, :destroy]

  # GET /employes
  # GET /employes.json
  def index
    @employes = Employe.all
  end

  # GET /employes/1
  # GET /employes/1.json
  def show
  end

  # GET /employes/new
  def new
    @employe = Employe.new
  end

  # GET /employes/1/edit
  def edit
  end

  # POST /employes
  # POST /employes.json
  def create
    @employe = Employe.new(employe_params)

    respond_to do |format|
      if @employe.save
        format.html { redirect_to @employe, notice: 'Employe was successfully created.' }
        format.json { render :show, status: :created, location: @employe }
      else
        format.html { render :new }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employes/1
  # PATCH/PUT /employes/1.json
  def update
    respond_to do |format|
      if @employe.update(employe_params)
        format.html { redirect_to @employe, notice: 'Employe was successfully updated.' }
        format.json { render :show, status: :ok, location: @employe }
      else
        format.html { render :edit }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employes/1
  # DELETE /employes/1.json
  def destroy
    @employe.destroy
    respond_to do |format|
      format.html { redirect_to employes_url, notice: 'Employe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employe
      @employe = Employe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employe_params
      params.require(:employe).permit(:name, :lastName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employes_helper.rb
module EmployesHelper
end

app/views/employes/_form.html.erb
<%= form_with(model: employe, local: true) do |form| %>
  <% if employe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employe.errors.count, "error") %> prohibited this employe from being saved:</h2>

      <ul>
        <% employe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employes/edit.html.erb
<h1>Editing Employe</h1>

<%= render 'form', employe: @employe %>

<%= link_to 'Show', @employe %> |
<%= link_to 'Back', employes_path %>

app/views/employes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employes.each do |employe| %>
      <tr>
        <td><%= employe.name %></td>
        <td><%= employe.lastName %></td>
        <td><%= link_to 'Show', employe %></td>
        <td><%= link_to 'Edit', edit_employe_path(employe) %></td>
        <td><%= link_to 'Destroy', employe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employe', new_employe_path %>

app/views/employes/new.html.erb
<h1>New Employe</h1>

<%= render 'form', employe: @employe %>

<%= link_to 'Back', employes_path %>

app/views/employes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employe.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employe.lastName %>
</p>

<%= link_to 'Edit', edit_employe_path(@employe) %> |
<%= link_to 'Back', employes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>